/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tomkranis (https://sketchfab.com/tomkranis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-fox-by-pixelmannen-animated-371dea88d7e04a76af5763f2a36866bc
Title: Low poly fox by PixelMannen (Animated)
*/

import React, { useRef, useLayoutEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import scene from "~/assets/3d/fox.glb";

const Fox = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  // This effect will run whenever the currentAnimation prop changes
  useLayoutEffect(() => {
    // Object.values(actions).forEach((action) => action.stop());

    // if (actions[currentAnimation]) {
    //   actions[currentAnimation].play();
    // }
    actions["Take 001"].play();
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="animationsFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.fox_material}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="fox1" rotation={[-Math.PI / 2, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};
export default Fox;
